### ISSUE TITLE
No Model/Input/Context/Twig generation when recreating an existing controller

### ISSUE THREAD

**Issue by PelegBN** [beyerz/SimpleHMVCBundle#4]
If I'm trying to create a certain controller again [after deleting or changing the name of the previous one],
all of the other files [model/input/context/twig] doesn't get created

**Comment by beyerz** [comment]
I have checked the process and everything work as expected.

when creating a controller with multiple actions, each action will generate the following
Model
Input
Context
View

**Comment by PelegBN** [comment]
Let's agree to disagree... 😌
